### PR TITLE
Update data.md

### PR DESCRIPTION
**Pull request by andreamedinasmith**
add in content from HackMD document

### CODE REVIEW

**Comment by yochannah** [comment]
Thank you!!

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @yochannah for mentoring

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @natashabatalha for mentoring

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @shilaan for mentoring

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @selgebali for mentoring

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @camriddell for mentoring

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @dutc for mentoring

**Pull request merged**
